const coupleQuotes = [
  "Love is sharing the last slice of pizza... and not holding a grudge.",
  "You two are proof that WiFi and Bluetooth can’t compete with real connection.",
  "Couple goals: arguing over the remote but still cuddling after.",
  "You’re like Netflix and chill—better together.",
  "Love is when ‘I’ becomes ‘we’... and ‘mine’ becomes ‘ours.’",
  "You two are the reason emojis have couple options.",
  "Relationship status: stealing each other’s fries since forever.",
  "You’re like a WiFi signal—stronger when closer.",
  "Love is letting them have the last piece of cake... sometimes.",
  "You two are the real-life version of ‘happily ever after.’",
  "Love is when you argue over who loves the other more.",
  "You two are like a hashtag—always connected.",
  "Couples who laugh together, stay together.",
  "Love is when you’re still their favorite notification.",
  "You’re like peanut butter and jelly—better as a pair.",
  "Relationship status: stealing their hoodies since day one.",
  "Love is when you’re their favorite hello and hardest goodbye.",
  "You two are like a perfect selfie—no filter needed.",
  "Love is when you’re their favorite playlist on repeat.",
  "You’re like coffee and mornings—better together.",
  "Couples who meme together, stay together.",
  "Love is when you’re their favorite home screen.",
  "You two are like a good Wi-Fi connection—always in sync.",
  "Love is when you’re their favorite notification sound.",
  "You’re like a good book—they can’t put you down.",
  "Couples who snack together, stay together.",
  "Love is when you’re their favorite emoji.",
  "You two are like a perfect pair of socks—always matching.",
  "Love is when you’re their favorite app—always open.",
  "You’re like a good song—they can’t get enough of you.",
  "Couples who game together, stay together.",
  "Love is when you’re their favorite notification pop-up.",
  "You two are like a perfect pair of shoes—made for each other.",
  "Love is when you’re their favorite meme.",
  "You’re like a good cup of tea—warm and comforting.",
  "Couples who travel together, stay together.",
  "Love is when you’re their favorite playlist.",
  "You two are like a perfect pair of gloves—always fitting.",
  "Love is when you’re their favorite GIF.",
  "You’re like a good movie—they never want it to end.",
];

export default coupleQuotes;
